### ISSUE TITLE
SSE stops working after a while idle

### ISSUE THREAD

**Issue by doodyparizada** [kinfoundation/kin-core-python#21]
### SDK version and Python version
using python3.6 and sdk version 80d7767af6d7dd2ec590720c9083ad7fe3346e2e
### OS version
mac osx 10.12.6
### The issue you are encountering including a stacktrace if applicable
Exception received after a while running idle:
```
Resetting dropped connection: horizon-testnet.stellar.org
https://horizon-testnet.stellar.org:443 "GET //accounts/GC3VEVNMPOIFIQOKUYFROWR6LWQQM57OQSWLLD6TGDIPOA5S6UXQWHVL/transactions/ HTTP/1.1" 504 0
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/Users/doody/.local/share/virtualenvs/payment-service-aFI30RhE/lib/python3.6/site-packages/urllib3/response.py", line 543, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/doody/.local/share/virtualenvs/payment-service-aFI30RhE/lib/python3.6/site-packages/urllib3/response.py", line 302, in _error_catcher
    yield
  File "/Users/doody/.local/share/virtualenvs/payment-service-aFI30RhE/lib/python3.6/site-packages/urllib3/response.py", line 598, in read_chunked
    self._update_chunk_length()
  File "/Users/doody/.local/share/virtualenvs/payment-service-aFI30RhE/lib/python3.6/site-packages/urllib3/response.py", line 547, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/doody/.local/share/virtualenvs/payment-service-aFI30RhE/lib/python3.6/site-packages/requests/models.py", line 745, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/Users/doody/.local/share/virtualenvs/payment-service-aFI30RhE/lib/python3.6/site-packages/urllib3/response.py", line 432, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/Users/doody/.local/share/virtualenvs/payment-service-aFI30RhE/lib/python3.6/site-packages/urllib3/response.py", line 626, in read_chunked
    self._original_response.close()
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/doody/.local/share/virtualenvs/payment-service-aFI30RhE/lib/python3.6/site-packages/urllib3/response.py", line 320, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/doody/.local/share/virtualenvs/payment-service-aFI30RhE/lib/python3.6/site-packages/sseclient.py", line 65, in __next__
    next_chunk = next(self.resp_iterator)
  File "/Users/doody/.local/share/virtualenvs/payment-service-aFI30RhE/lib/python3.6/site-packages/requests/models.py", line 748, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/doody/.local/share/virtualenvs/payment-service-aFI30RhE/src/kin/kin/sdk.py", line 512, in event_processor
    for event in events:
  File "/Users/doody/.local/share/virtualenvs/payment-service-aFI30RhE/lib/python3.6/site-packages/sseclient.py", line 72, in __next__
    self._connect()
  File "/Users/doody/.local/share/virtualenvs/payment-service-aFI30RhE/lib/python3.6/site-packages/sseclient.py", line 52, in _connect
    self.resp.raise_for_status()
  File "/Users/doody/.local/share/virtualenvs/payment-service-aFI30RhE/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: GATEWAY_TIMEOUT for url: https://horizon-testnet.stellar.org//accounts/GC3VEVNMPOIFIQOKUYFROWR6LWQQM57OQSWLLD6TGDIPOA5S6UXQWHVL/transactions/
```
### Steps or a code snippet to reproduce the issue
For example this code will produce the error after a while:
```python
def print_me(address, data):
    try:
        print('='*100)
        print('got data1:', address, data)
        print('='*100)
    except Exception as e:
        print('failed', e)

kin_sdk.monitor_accounts_kin_payments([address], print_me)
```

**Comment by bolshoy** [comment]
fixed it by adding 504 to the list of retry statuses
